### ISSUE TITLE
nice READme and Schema

### ISSUE THREAD

**Issue by amberrignell** [fac20/WEEK5-ACDO#36]
Nice one including your schema in the READme.

If you had more time you could also include instructions about how to install and run your code as well as the tests, and maybe the list of acceptance criteria so that we can see which ones you've managed to tick off

**Comment by akomiqaia** [comment]
It is always a good idea to write your documentation as you go. The database setup part is quite important and all the important parts have to be part of your readme. As a developer, I might be very confused about what shall I do with this code. :D

**Comment by amberrignell** [comment]
Don't forget to also tell the developer looking at your code that if he wants to get it working on his local server he needs to initialise a local database and put the database url into the .env file etc
